### ISSUE TITLE
influxdb import error because of same name in python 2.7

### ISSUE THREAD

**Issue by aiden0z** [fraoustin/flask-monitor#5]
```
In [1]: from flask_monitor.influxdb import ObserverInfluxdb
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-af3fa41583b3> in <module>()
----> 1 from flask_monitor.influxdb import ObserverInfluxdb

/home/aiden0z/app/env/local/lib/python2.7/site-packages/flask_monitor/influxdb.py in <module>()
      3 from flask_monitor import ObserverMetrics
      4
----> 5 from influxdb import InfluxDBClient
      6 from influxdb.client import InfluxDBClientError
      7
```

**Comment by fraoustin** [comment]
Hi 
have you installed the module "influxdb" by pip ?

> pip install influxdb

If yes, you can test in the python console

> import influxdb
> from influxdb import InfluxDBClient

Thank you for test

**Comment by rickard-von-essen** [comment]
I can confirm this:

```
Python 2.7.10 (default, Jul 15 2017, 17:16:57)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import influxdb
>>> from influxdb import InfluxDBClient
>>> from flask_monitor.influxdb import ObserverInfluxdb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rickardvonessen/Library/Python/2.7/lib/python/site-packages/flask_monitor/influxdb.py", line 5, in <module>
    from influxdb import InfluxDBClient
ImportError: cannot import name InfluxDBClient
>>>
```

**Comment by Toe-Hlaing-Win** [comment]
I also have that error bros. 
What was the fix, Please

**Comment by fraoustin** [comment]
Hi
the problem exist only python2.7 (it's work on 3.5)
I search a solution without impact

**Comment by fraoustin** [comment]
The new version 0.2.6 is your solution
